name: dreamer-env
channels:
  - defaults
  - conda-forge
dependencies:
   - python=3.8
   - pip
   - git
   - mesalib
   - patchelf
   - ffmpeg
   - cudatoolkit=10.1.243
   - cudnn=7.6.5
   - pip:
       - -r file:requirements.txt
